/**
 * PubSub 事件名称
 */

const topics = {
  // store 相关
  SET_TOKEN: 'SET_TOKEN',
  REMOVE_TOKEN: 'REMOVE_TOKEN',
  SET_USERINFO: 'SET_USERINFO',
  REMOVE_USERINFO: 'REMOVE_USERINFO',
  SET_ROLE: 'SET_ROLE',
  REMOVE_ROLE: 'REMOVE_ROLE',
  SET_RESOURCE: 'SET_RESOURCE',
  REMOVE_RESOURCE: 'REMOVE_RESOURCE',
  TOGGLE_SIDEBAR_COLLAPSE: 'TOGGLE_SIDEBAR_COLLAPSE',

  // 业务相关

}

export default topics
